{% set name = "tvb-storage" %}
{% set version = "2.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1af5586db3adeda02089a9cccd16dbfec1fc5bd1df1e4985fba5837efa72debc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - h5py
    - numpy
    - scipy
    - tvb-library

test:
  requires:
    - pytest
    - pip

  commands:
#     - pip check
    - pytest --pyargs tvb.tests.storage

  imports:
    - tvb.storage

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A package for performing whole brain simulations
  description: |
    The Virtual Brain Project (TVB Project) has the purpose of offering some |
    modern tools to the Neurosciences community, for computing, simulating |
    and analyzing functional and structural data of human brains. |
    The Virtual Brain framework is a complete framework including: |
    -  a plugable workflow manager; |
    -  a data persistence layer (with a relational DB and File Storage HDF5); |
    -  an HTML5 based user interface; |
    -  visualizers for neuro-science related entities.
    -  REST server and client SDK
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-root

extra:
  recipe-maintainers:
    - liadomide
    - popaula937
